#For full documentation of the parameters in this file, and a list of all the
#parameters available for TrajectoryPlannerROS, please see
#http://www.ros.org/wiki/base_local_planner
TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 10.5
  min_vel_theta: -10.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 10.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  vtheta_samples: 40

  escape_reset_dist: 0.25

  sim_time: 5

  holonomic_robot: false