# The ZED camera and the simulator one use different coordinate systems,
# so we need separate configs for them.

# For the ZED camera, the z axis is the height
filter_field_name: z
filter_limit_max: 3.0
filter_limit_min: -0.10
filter_limit_negative: false
leaf_size: 0.1
