# The frame which will be used to compare distance and rotation to
base_link_frame: "chassis_link"

# The offset of the tag from the base frame
offset:
  x: 0.64
  y: 0.0
  th: 0.0

# Number of retries (dock/undock cycles) before failing
max_retries: 3

# Offset in forward axis when undocking
retry_offset: 1.6

# Number of cycles to try to put robot within error margins before retrying
retry_error_times: 50

# Accepted threshold for x (forward) error
thresh_x: 0.01

# Accepted threshold for y (lateral) error
thresh_y: 0.02

#Accepted threshold for th (angular) error
thresh_th: 0.045
