# The frame which will be used to compare distance and rotation to
base_link_frame: "chassis_link"
lidar_frame: "rear_laser"

use_lidar: true

included_lidar_measures: [ 2, 3, 4, 5, 6, 7, 8 ]

# The angle that objects are detected within by the rear lidar 
rear_lidar_angle: 1.57079632679

# The angle that objects are detected within by the front lidar 
front_lidar_angle: 1.57079632679

# The max number of seconds it can be since last laser scan
max_time_since_lidar_scan: 0.5

# Number of retries (dock/undock cycles) before failing
max_retries: 5

# Number of cycles to try to put robot within error margins before retrying
retry_error_times: 50

# true to publsh visualization markers that can be shown in rviz. Shows robot distance along tag norm and dist to tag norm.
debug: false
