!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  a: -0.02
  b: 10.0
  c: -3.9
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Docking_Offsets: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              name: Docking_Offsets
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              th_desired_offset: 0.0
              type: ''
              x_desired_offset: 0.75
              x_desired_retry_offset: 1.6
              y_desired_offset: 0.0
            state: []
          Docking_Speeds: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              max_docking_speed: 0.15
              max_rotation_speed: 0.2
              max_undocking_speed: 0.15
              name: Docking_Speeds
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          Docking_Thresholds: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              name: Docking_Thresholds
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              th_error_thresh: 0.02
              type: ''
              x_error_thresh: 0.01
              y_error_thresh: 0.01
            state: []
          Object_Avoidabce: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 5
              min_dist_to_object_behind: 0.3
              min_dist_to_object_infront: 0.3
              min_dist_to_wall: 0.05
              name: Object_Avoidabce
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
          RearLidar_Usage: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 6
              lidar_contrib_factor: 40.0
              lidar_contrib_offset: 3.0
              name: RearLidar_Usage
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              rear_lidar_angle_offset: 0.0025
              state: true
              type: ''
            state: []
          Rotation_Calculation: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              a: -0.02
              b: 10.0
              c: -3.9
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              name: Rotation_Calculation
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              state: true
              type: ''
            state: []
        state: []
      id: 0
      max_tf_lookup_time: 2.0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  lidar_contrib_factor: 40.0
  lidar_contrib_offset: 3.0
  max_docking_speed: 0.15
  max_rotation_speed: 0.2
  max_tf_lookup_time: 2.0
  max_undocking_speed: 0.15
  min_dist_to_object_behind: 0.3
  min_dist_to_object_infront: 0.3
  min_dist_to_wall: 0.05
  rear_lidar_angle_offset: 0.0025
  th_desired_offset: 0.0
  th_error_thresh: 0.02
  x_desired_offset: 0.75
  x_desired_retry_offset: 1.6
  x_error_thresh: 0.01
  y_desired_offset: 0.0
  y_error_thresh: 0.01
state: []
