# Overall filter parameters
min_particles:        100      # 100,500
max_particles:        5000     # 5000
kld_err:              0.01      # 0.01, 0.05
kld_z:                0.99      # 0.99
update_min_d:         0.1       # 0.2
update_min_a:         0.1   # 0.5235
resample_interval:    1        # 2, 1
transform_tolerance:  0.2       # 0.1, 0.2
recovery_alpha_slow:  0.0     # 0.0, 0.0, 0.001
recovery_alpha_fast:  0.1       # 0.0, 0.0, 0.1
initial_pose_x:       0.0       # 0.0
initial_pose_y:       0.0       # 0.0 
initial_pose_a:       0.0       # 0.0
initial_cov_xx:       0.25      # 0.25
initial_cov_yy:       0.25      # 0.25
initial_cov_aa:       0.06853   # 0.06853 
gui_publish_rate:     -1.0      # -1.0, 10
save_pose_rate:       0.5       # 0.5
use_map_topic:        true      # false
first_map_only:       false     # false

# Laser Model Parameters 
laser_min_range:            0.2   # -1.0
laser_max_range:            -1.0   # -1.0
laser_max_beams:            360    # 180
laser_z_hit:                0.95   # 0.95, 0.5
laser_z_short:              0.05    # 0.1,  0.05
laser_z_max:                0.05   # 0.05 
laser_z_rand:               0.75   # 0.05, 0.5
laser_sigma_hit:            0.5    # 0.2   
laser_lambda_short:         0.1    # 0.1
laser_likelihood_max_dist:  2.0    # 2.0
laser_model_type:           likelihood_field_prob

# Odometery model parameters
odom_model_type:  diff
odom_alpha1:      0.3   # 0.2 rr
odom_alpha2:      0.1   # 0.2 rt
odom_alpha3:      0.05    # 0.2,0.8 tt
odom_alpha4:      0.1   # 0.2 tr
odom_alpha5:      0.2    # 0.2,0.1
odom_frame_id:    odom_chassis
base_frame_id:    chassis_link
global_frame_id: map
tf_broadcast: false
