publish_poses: true

goals:
    - x: -2.0
      y: 2.0
      th: 0.0
      lift: 0
    - x: 0.0
      y: 0.0
      th: 0.0
      lift: 1
    - x: -1.0
      y: 4.0
      th: 3.14
      lift: 0
    - x: 0.0
      y: 0.0
      th: 0.0
      lift: 2
