#map_frame: map 
odom_frame: odom_chassis
base_link_frame: chassis_link
world_frame: map

two_d_mode: true

frequency: 50
#(X,Y,Z,
#roll,pitch,yaw,
#X˙,Y˙,Z˙,
#roll˙,pitch˙,yaw˙,
#X¨,Y¨,Z¨)


# odom/wheel

odom0: wheelencoder/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10
