footprint: [[-0.5, -0.3], [-0.5, 0.3], [0.2, 0.3], [0.2, -0.3]]
footprint_padding: 0.0

#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.3


#Cost function parameters
inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 2.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
static_map:
    lethal_cost_threshold: 250


#Obstacle marking parameters
obstacle_layer:
    obstacle_range: 3.0
    max_obstacle_height: 2.0
    raytrace_range: 3.0

    #Configuration for the sensors that the costmap will use to update a map
    observation_sources: laser_scan_sensor point_cloud_sensor

    #testing with 360 degrees of view from LIDAR
    laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: /frontLidar/scan, expected_update_rate: 0.5,
    marking: true, clearing: true, max_obstacle_height: 1, min_obstacle_height: 0.08}

    #Stereo camera params
    point_cloud_sensor: {sensor_frame: zed_left_camera_optical_frame, data_type: PointCloud2, topic: /zed/depth/points_filtered, expected_update_rate: 1.0,
    marking: true, clearing: true, max_obstacle_height: 3.0, min_obstacle_height: 0.1}
