# #Independent settings for the global planner's costmap.
# #Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d
#
# All distances are in meters

global_costmap:
  plugins:
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

  #Set the update and publish frequency of the costmap
  update_frequency: 10.0
  publish_frequency: 0.0

  #We'll use a map served by the map_server to initialize this costmap
  static_map: true
  rolling_window: false

  footprint_padding: 0.02
