# #Independent settings for the global planner's costmap.
# #Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d
#
# #All distances are in meters
#
# global_costmap:
#   #Set the global and robot frames for the costmap
#   plugins:
#     - {name: static_layer,     type: "costmap_2d::StaticLayer"}
#     - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
#
#   global_frame: /map
#   robot_base_frame: base_link
#
#   #Set the update and publish frequency of the costmap
#   update_frequency: 1
#   publish_frequency: 0.5
#
#   #We'll use a map served by the map_server to initialize this costmap
#   static_map: true
#   rolling_window: false
#   use_first_map_only: true
#   resolution: 0.1
#
#   inflation_layer:
#     inflation_radius: 0.55
#     cost_scaling_factor: 10
#

global_costmap:

  plugins:
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
  # - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: static_layer,     type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
    #- {name: voxel_layer,       type: "costmap_2d::VoxelLayer"}


     #Independent settings for the local planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_costmap:
  #Set the global and robot frames for the costmap
  global_frame: map
  #robot_base_frame: base_link_gazebo
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 10.0
  publish_frequency: 0.0

  #We'll use a map served by the map_server to initialize this costmap
  static_map: true
  rolling_window: false

  footprint_padding: 0.02

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 0.5

